/*
 * Void, a modification for grok.com
 * Copyright (c) 2026 Void contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

export const SERIALIZE = {
    DEFAULT_DEPTH: 2,
    MAX_ARRAY: 30,
    MAX_KEYS: 20,
    MAX_STRING_LENGTH: 200,
} as const;

export const SEARCH = {
    MAX_TOTAL: 30_000,
    DEFAULT_MAX: 10,
    DEFAULT_CONTEXT: 60,
    MAX_CONTEXT: 200,
    MAX_RESULTS_CAP: 50,
    MAX_MATCH_LENGTH: 500,
} as const;

export const MODULE = {
    DEFAULT_SOURCE_LIMIT: 4000,
    MAX_SOURCE_LIMIT: 50_000,
    EXPORT_VALUE_SLICE: 50,
    EXPORT_KEYS_PREVIEW: 5,
    DEFAULT_EXPORT_KEYS: 50,
    MAX_EXPORT_KEYS: 100,
    DEFAULT_DIFF_SLICE: 4000,
    MAX_DIFF_SLICE: 10_000,
    DEFAULT_FIND_ALL: 15,
    MAX_FIND_ALL: 50,
    DEFAULT_WHERE_USED: 50,
    MAX_WHERE_USED: 200,
    WHERE_USED_LIMIT: 50,
    SUGGEST_MIN_LEN: 6,
    DEFAULT_SUGGEST: 30,
    MAX_SUGGEST: 50,
    DEFAULT_FUNCTION_AT: 8000,
    FUNCTION_AT_MAX: 8000,
    FUNCTION_AT_HEADER_MAX: 200,
    FUNCTION_AT_FORWARD: 500,
    FUNCTION_AT_LOOKBACK: 200,
    DIFF_CONTEXT_PAD: 60,
    DIFF_SCAN_LIMIT: 5000,
    DIFF_RESYNC_SLICE: 20,
    DIFF_UNSYNCED_CONTEXT: 200,
    EXPORT_KEYS_SLICE: 10,
    SEARCH_CONTEXT_PAD: 200,
    DEFAULT_UNLOADED_LIMIT: 20,
    MAX_UNLOADED_LIMIT: 50,
    UNLOADED_PREVIEW_LENGTH: 120,
} as const;

export const PATCH = {
    FIND_SLICE: 120,
    ANALYZE_IDS_LIMIT: 20,
    NOT_UNIQUE_IDS_LIMIT: 10,
    MATCH_SLICE: 300,
    GROUP_SLICE: 100,
    DEFAULT_CONTEXT_PAD: 150,
    MAX_CONTEXT_PAD: 500,
    HINT_LITERAL_SLICE: 30,
    MAX_CAPTURE_WARN: 5,
    CONTEXT_DEFAULT_WINDOW: 1500,
    CONTEXT_MAX_WINDOW: 5000,
    CONTEXT_MIN_WINDOW: 50,
    CONTEXT_MAX_ANCHORS: 30,
    MATCH_WARN_LENGTH: 80,
    MATCH_LONG_LENGTH: 200,
    ANALYZE_DEFAULT_CONTEXT: 300,
    MIN_LITERAL_LENGTH: 3,
} as const;

export const REACT = {
    MAX_DEPTH: 30,
    DEFAULT_DEPTH: 10,
    MAX_LIMIT: 30,
    DEFAULT_LIMIT: 15,
    MAX_BREADTH: 15,
    DEFAULT_BREADTH: 6,
    MAX_TREE_DEPTH: 3,
    MAX_PROCESS: 5_000,
    MAX_NAMED: 150,
    MAX_HOOKS: 20,
    MAX_STATE_VALUES: 15,
    PROP_KEYS_PREVIEW: 8,
    FIBER_PROP_KEYS: 10,
    TEXT_SLICE: 60,
    WALK_UP_DEPTH: 5,
    MAX_CLASS_PREVIEW: 5,
    MIN_COMPONENT_NAME: 3,
} as const;

export const STORE = {
    DEFAULT_DURATION: 10_000,
    MIN_DURATION: 1000,
    MAX_DURATION: 60_000,
    DEFAULT_CAPTURES: 50,
    MAX_CAPTURES: 200,
    KEYS_PREVIEW: 10,
    SIMILAR_LIMIT: 5,
    LIST_KEYS_PREVIEW: 8,
    METHODS_PREVIEW: 10,
    MAX_DEPTH: 4,
    DEFAULT_DEPTH: 2,
    SUBSCRIBE_DEPTH: 1,
    MINIFIED_STORE_NAME: "r",
} as const;

export const INTERCEPT = {
    DEFAULT_DURATION: 30_000,
    MIN_DURATION: 5000,
    MAX_DURATION: 120_000,
    DEFAULT_CAPTURES: 50,
    MAX_CAPTURES: 200,
    GET_CAPTURES_LIMIT: 50,
    SERIALIZE_DEPTH: 2,
} as const;

export const MCP = {
    SLOW_THRESHOLD: 1000,
    MAX_RESULT_SIZE: 50_000,
    INITIAL_RECONNECT_DELAY: 3000,
    MAX_RECONNECT_DELAY: 60_000,
    RELOAD_DELAY: 200,
    TRUNCATION_THRESHOLD: 20_000,
    MIN_TRUNCATED_ITEMS: 5,
    MIN_TRUNCATED_NESTED: 3,
    REQUEST_TIMEOUT: 30_000,
    WS_OPEN: 1,
    PORT: 7890,
} as const;

export const GROK = {
    BYTES_PER_MB: 1_048_576,
    MAX_FEATURE_RESULTS: 50,
} as const;

export const EVAL = {
    MAX_CODE_LENGTH: 10_000,
    SERIALIZE_DEPTH: 3,
    STACK_LINES: 3,
} as const;
