import type { FileMetadata } from "../common/Asset";
import type { ResponseSender } from "../enums/conversation";
import type { ZustandStore } from "../zustand";

/**
 * A Grok response (message) object as returned by the responses API.
 * Represents a single message in a conversation, from either the user or the model.
 */
export interface GrokResponse {
    /** Unique response UUID. */
    responseId: string;
    /** The text content of the response (markdown). */
    message: string;
    /** Who sent this response (e.g. "human", "assistant"). */
    sender: ResponseSender;
    /** ISO 8601 timestamp of when the response was created. */
    createTime: string;
    /** Parent response ID for branching conversations (thread support). */
    parentResponseId?: string;
    /** Whether this response was manually entered (not generated). */
    manual?: boolean;
    /** Whether this response is still being streamed (partial content). */
    partial?: boolean;
    /** Whether this response has been shared publicly. */
    shared?: boolean;
    /** The user's query text that prompted this response. */
    query?: string;
    /** Type of query (e.g. "DEFAULT", "REASONING"). */
    queryType?: string;
    /** Web search results cited in this response. */
    webSearchResults?: any[];
    /** X (Twitter) post IDs referenced in this response. */
    xpostIds?: string[];
    /** Full X post objects embedded in this response. */
    xposts?: any[];
    /** URLs of images generated by this response. */
    generatedImageUrls?: string[];
    /** Image attachments uploaded by the user. */
    imageAttachments?: any[];
    /** File attachments uploaded by the user. */
    fileAttachments?: any[];
    /** JSON-encoded card attachment data. */
    cardAttachmentsJson?: string[];
    /** File URIs for uploaded files. */
    fileUris?: string[];
    /** Metadata for file attachments (name, size, type, etc.). */
    fileAttachmentsMetadata?: FileMetadata[];
    /** Whether this is a control message (not displayed to user). */
    isControl?: boolean;
    /** Reasoning/thinking trace text shown in "think" mode. */
    thinkingTrace?: string;
    /** Tool execution steps performed during generation. */
    steps?: any[];
    /** URI for an edited image result. */
    imageEditUri?: string;
    /** URIs for multiple edited image results. */
    imageEditUris?: string[];
    /** Error information if the response failed. */
    error?: any;
    /** Media types used in this response. */
    mediaTypes?: string[];
    /** URLs of web pages browsed during generation. */
    webpageUrls?: string[];
    /** Arbitrary metadata attached to this response. */
    metadata?: Record<string, any>;
    /** Height of generated images in pixels. */
    generatedImageHeight?: number;
    /** Width of generated images in pixels. */
    generatedImageWidth?: number;
    /** UI layout configuration for response rendering. */
    uiLayout?: any;
    /** Timestamp when the model started its thinking/reasoning phase. */
    thinkingStartTime?: string;
    /** Timestamp when the model finished its thinking/reasoning phase. */
    thinkingEndTime?: string;
    /** Web search results that were actually cited in the response text. */
    citedWebSearchResults?: any[];
    /** Selected text content from uploaded files. */
    selectedFileTextContent?: string;
    /** Start position of selected file text. */
    selectedFileTextContentStartPosition?: number;
    /** End position of selected file text. */
    selectedFileTextContentEndPosition?: number;
    /** Tool response payloads from function calls. */
    toolResponses?: any[];
    /** Parent message ID for thread replies. */
    threadParentId?: string;
    /** Quoted text from the parent message. */
    parentQuotedText?: string;
    /** Model identifier that generated this response. */
    model?: string;
    /** Side-by-side comparison configuration. */
    sideBySideConfig?: any;
    /** Fast tool response data (inline tool results). */
    fastToolResponse?: any;
    /** Request metadata (model, mode, effort level) for this response. */
    requestMetadata?: {
        model?: string;
        mode?: string;
        effort?: any;
    };
}

/**
 * A node in the conversation response tree.
 * Used for branching conversation support (multiple response paths).
 */
export interface ResponseNode {
    /** The response ID this node represents. */
    responseId: string;
    /** Child response IDs branching from this node. */
    children: string[];
}

/**
 * Zustand state for response (message) management.
 *
 * Module ID: **159422**. Manages all responses across conversations,
 * including caching, streaming, pagination, branching (nodes), and
 * optimistic updates. The most data-heavy store in Grok.
 */
export interface ResponseStoreState {
    /** In-flight node tree fetch promises keyed by conversation ID. */
    nodesPromisesByConversationId: Record<string, Promise<any>>;
    /** Response tree nodes keyed by conversation ID. */
    nodesByConversationId: Record<string, ResponseNode[]>;
    /** In-flight initial response load promises keyed by conversation ID. */
    initialResponsesPromisesByConversationId: Record<string, Promise<any>>;
    /** In-flight "load more" pagination promises keyed by conversation ID. */
    loadMoreResponsesPromisesByConversationId: Record<string, Promise<any>>;
    /** In-flight preview response promises keyed by "conversationId:responseId". */
    previewResponsesPromisesByConversationIdResponseId: Record<string, Promise<any>>;
    /** In-flight image response promises keyed by conversation ID. */
    conversationImageResponsesPromisesByConversationId: Record<string, Promise<any>>;
    /** All cached responses keyed by response ID. */
    byId: Record<string, GrokResponse>;
    /** Response ID lists keyed by conversation ID. */
    byConversationId: Record<string, string[]>;
    /** Image ID lookup keyed by image URL. */
    imageIdByUrl: Record<string, string>;
    /** In-flight streaming promises keyed by conversation ID. */
    inflightPromisesByConversationId: Record<string, Promise<any>>;

    /** Insert or update a single response in the cache. */
    upsertResponse: (response: GrokResponse) => void;
    /** Insert or update multiple responses at once. */
    upsertResponses: (responses: GrokResponse[]) => void;
    /** Update specific fields on an existing response. */
    updateResponse: (id: string, updates: Partial<GrokResponse>) => void;
    /** Append responses to a conversation's response list. */
    appendResponses: (responses: GrokResponse[]) => void;
    /** Remove a response from the cache. */
    removeResponse: (id: string) => void;
    /** Clear all cached response data (logout/reset). */
    clear: () => void;

    // ── Data Loading ────────────────────────────────────────────────────

    /** Fetch the response node tree for a conversation. */
    fetchListResponseNodes: (conversationId: string) => Promise<any>;
    /** Fetch in-flight (still streaming) responses for a conversation. */
    fetchListInflightResponses: (conversationId: string) => Promise<any>;
    /** Load responses for a conversation with caching. */
    loadResponses: (conversationId: string, options?: any) => Promise<any>;
    /** Load the initial page of responses for a conversation. */
    loadInitialResponses: (conversationId: string, options?: any) => Promise<any>;
    /** Load the next page of responses (pagination). */
    loadMoreResponses: (conversationId: string, options?: any) => Promise<any>;
    /** Load preview responses for a specific response branch. */
    loadPreviewResponses: (conversationId: string, responseId?: any) => Promise<any>;
    /** Load a specific branch of the conversation tree. */
    loadConversationBranch: (conversationId: string, branchId: string, options?: any) => Promise<any>;
    /** Load image-specific responses for a conversation. */
    loadConversationImageResponses: (conversationId: string) => Promise<any>;
    /** Load thread messages for a specific parent message. */
    loadThreadMessages: (conversationId: string, options?: any) => Promise<any>;

    // ── Streaming ───────────────────────────────────────────────────────

    /** Close stale streaming responses and upsert a new one. */
    closeStaleResponsesInConversationAndUpsert: (conversationId: string, response: GrokResponse) => void;
    /** Start streaming a response from the model. */
    streamResponse: (params: any) => Promise<any>;
    /** Reconnect to an in-flight streaming response after page reload. */
    reconnectToResponse: (params: any) => Promise<any>;
    /** Create a new conversation and stream the first response. */
    streamCreateAndRespond: (params: any) => Promise<any>;
    /** Abort a streaming response. */
    abortStream: (conversationId: string, responseId: string, options?: any) => Promise<void>;
    /** Add a user-sent response to the conversation. */
    addUserResponse: (conversationId: string, message: string, options?: any) => Promise<any>;
    /** Add a tool-generated response. */
    addToolResponse: (conversationId: string, response: any) => Promise<any>;
    /** Create a voice mode user message. */
    createVoiceUserMessage: (params: any) => Promise<any>;
}

/** Module exports for the Response store (module **159422**). */
export interface ResponseStoreModule {
    /** Zustand store hook for response state. */
    useResponseStore: ZustandStore<ResponseStoreState>;
    /** Default number of images to generate (2). */
    DEFAULT_IMAGE_GEN_COUNT: number;
    /** Build tool usage trace from response step data. */
    buildToolUsageAndTraceFromSteps: () => any;
    /** Create an optimistic response object before the server responds. */
    createOptimisticResponse: (params: any) => GrokResponse;
    /** Check if a response is in a thinking/reasoning state. */
    isThinkingOrReasoning: (response: GrokResponse) => boolean;
    /** Handle a soft stop event during streaming. */
    maybeHandleSoftStop: (a: any, b: any, c: any) => void;
    /** Process a chunk of response data during streaming. */
    maybeProcessResponseChunk: (a: any, b: any, c: any) => void;
    /** Process a chunk of user data during streaming. */
    maybeProcessUserChunk: (a: any, b: any, c: any) => void;
    /** Zod-like schema for response metadata validation. */
    responseMetadataSchema: any;
    /** Hook to subscribe to a specific response by conversation and response ID. */
    useResponse: (conversationId: string, responseId: string) => GrokResponse | undefined;
}
