import type {
	ArtifactInlineStatus,
	FileCategory,
	FileSourceType,
	FileTypeId,
} from "../enums/files";

/**
 * Asset metadata as returned by the asset repository API.
 *
 * Represents a file or artifact stored in Grok's asset system. Assets can be
 * user-uploaded files, model-generated code artifacts, or third-party integrations
 * (Google Drive, OneDrive).
 */
export interface AssetMetadata {
	/** Unique asset UUID. */
	assetId: string;
	/** MIME type of the asset (e.g. "text/plain", "application/pdf"). */
	mimeType: string;
	/** Display name of the asset (usually the original file name). */
	name: string;
	/** File size in bytes. */
	sizeBytes: number;
	/** ISO 8601 timestamp of asset creation. */
	createTime: string;
	/** ISO 8601 timestamp of last modification. */
	updateTime: string;
	/** ISO 8601 timestamp of last access/use. */
	lastUseTime: string;
	/** AI-generated summary of the file contents. */
	summary: string;
	/** Storage key for the preview image thumbnail. */
	previewImageKey: string;
	/** Primary storage key for the asset content. */
	key: string;
	/** Auxiliary storage keys (e.g. different formats or versions). */
	auxKeys: Record<string, string>;
	/** Response ID that created this asset (for model-generated artifacts). */
	responseId: string;
	/** Whether the asset has been soft-deleted. */
	isDeleted: boolean;
	/** How the file was uploaded/created. */
	fileSource: FileSourceType;
	/** External file ID for third-party integrations (Google Drive, OneDrive). */
	thirdPartyFileId: string;
	/** MIME type from the third-party source (may differ from `mimeType`). */
	thirdPartyFileMimeType: string;
	/** Conversation ID where the asset is currently attached. */
	currentConversationId: string;
	/** Root asset ID for versioned artifacts (points to the original version). */
	rootAssetId: string;
	/** Conversation ID where the asset was originally created. */
	sourceConversationId: string;
	/** Diff content between this version and the previous. */
	assetDiff: string;
	/** Whether this asset was generated by the model (not user-uploaded). */
	isModelGenerated: boolean;
	/** Whether this is the latest version of a versioned artifact. */
	isLatest: boolean;
	/** How the artifact should be displayed (inline in chat vs sidebar). */
	inlineStatus: ArtifactInlineStatus;
	/** Whether the root version of this artifact was created by the model. */
	isRootAssetCreatedByModel: boolean;
	/** Conversation ID where the root asset was created. */
	rootAssetSourceConversationId: string;
	/** Sharing key for workspace-shared assets. */
	workspaceSharingKey: string;
	/** Sharing key for the preview image of workspace-shared assets. */
	workspaceSharingPreviewImageKey: string;
	/** Team ID the asset belongs to (for team workspaces). */
	teamId: string;
	/** Whether the asset is shared with the entire team. */
	sharedWithTeam: boolean;
	/** User IDs the asset is explicitly shared with. */
	sharedWithUserIds: string[];
	/** Whether the asset is publicly accessible. */
	isPublic: boolean;
	/** Image width in pixels (0 for non-image assets). */
	width: number;
	/** Image height in pixels (0 for non-image assets). */
	height: number;
	/** Whether the asset contains NSFW/adult content. */
	rRated: boolean;
}

/**
 * File metadata as used by the chat UI layer.
 *
 * This is the transformed shape created by `convertAssetMetadataToFileMetadata`,
 * used for rendering file chips, attachment previews, and file references in messages.
 */
export interface FileMetadata {
	/** File metadata ID (maps to asset's `assetId`). */
	fileMetadataId: string;
	/** Display file name. */
	fileName: string;
	/** MIME type of the file. */
	fileMimeType: string;
	/** Direct URI to the file content. */
	fileUri: string;
	/** URI to a parsed/preview version of the file. */
	parsedFileUri: string;
	/** ISO 8601 timestamp of creation. */
	createTime: string;
	/** How the file was uploaded. */
	fileSource: FileSourceType;
	/** External file ID for third-party files. */
	thirdPartyFileId: string;
	/** MIME type from the third-party source. */
	thirdPartyFileMimeType: string;
}

/**
 * A file type descriptor from Grok's `FILE_DESCRIPTIONS` registry.
 *
 * Each descriptor defines a recognized file type with its display name, icon,
 * associated extensions, MIME types, and UI color. Used by `getFileTypeIdForAsset`
 * and `getFileCategoryForAsset` to classify files.
 */
export interface FileTypeDescriptor {
	/** Unique identifier for this file type. */
	id: FileTypeId;
	/** Human-readable display name (e.g. "Python", "Markdown", "Image"). */
	name: string;
	/** High-level category grouping. */
	category: FileCategory;
	/** React icon component for this file type. */
	Icon: any;
	/** Default name for newly created files of this type. */
	newFileName: string;
	/** File extensions that map to this type (without dots). */
	extensions: string[];
	/** MIME type matcher: array of strings, RegExp, or function. */
	mime?: string[] | RegExp | ((mime: string) => boolean);
	/** Tailwind color classes for dark/light mode (e.g. "dark:text-blue-500 text-blue-400"). */
	color?: string;
}

/**
 * Search result from the asset repository.
 * Wraps asset metadata with highlighted search matches.
 */
export interface AssetSearchResult {
	/** The matched asset metadata. */
	assetMetadata: AssetMetadata;
	/** Highlighted content snippet matching the search query. */
	highlight?: string;
	/** Highlighted file name matching the search query. */
	nameHighlight?: string;
}
